### PR TITLE
Add hangman game interface

### PR DESCRIPTION
**Pull request by codeTravels**
I did not make any code changes it was only creating and implementing the new HangmanGame interface.

### CODE REVIEW

**Comment by codeTravels** [comment]
Do you think it is ok that HangmanGame extends Model (interface) even though HangmanGameImpl is extending AbstractModel to satisfy the interface? AbstractModel implements Model interface.

**Comment by orozcoadrian** [comment]
yea it looks a bit odd. i don't remember using an interface for the model...

maybe it'd help to write down what are the goals of your architecture. we can then evaluate design decisions against those goals. for example here's a few i would define for an app like this one:
1. goal: keep the UI separate from the core game logic. why? we'd like to be able to make tweaks to the UI and not have to worry about breaking core logic. also we may choose to have a different front-end (for example a javafx UI) and be able to re-use the backend.
2. goal: keep core logic testable (at least the core game logic but ideally everything). why? because we want to be confident that we haven't introduced regressions as we add new features, fix bugs, etc
3. goal: maximize use of data-binding. why? to avoid buggy ui-update logic for something that's already established (there are existing data-binding mechanisms that are tried-and-tested, why re-invent the wheel?)

note that having an interface for the UI (your current View interface) aligns with the first goal. having an interface for the model may align with the second one.. if in fact that's why you added it. if we can't find a goal to align the decision to add an interface for the model, then we're either missing a goal or we don't need an interface for the model.

**Comment by orozcoadrian** [comment]
you don't have to come up with all final goals up front. simply come up with the ones you know right now. you can change the list as you progress

**Comment by codeTravels** [comment]
I think the interface came about to have more separation of concerns and allow unit testing to be easier. Also I was watching an online course about TDD and had I started that way (using TDD) I would have defined the interactions you could have with the game. Creating the interface allows there to be a contract and hopefully one that does not change negatively

**Review by orozcoadrian — APPROVED** [review]

**Comment by orozcoadrian** [comment]
i agree that interfaces are good for sep of concerns. what i meant was that i don't think having one _**in model classes**_ helps much, if your model classes are simply "data holders".

checkout these two comments from a relevant thread on SO: [one](https://stackoverflow.com/a/2413625), [two](https://stackoverflow.com/a/2413526)

**Review by orozcoadrian — APPROVED** [review]

**Pull request merged**
