### PR TITLE
Add config menu

### PR DESCRIPTION
**Pull request by codeTravels**
Added a config menu and it currently only changes the number of guesses allowed.

### CODE REVIEW

**Comment by codeTravels** [comment]
I need to handle when I cancel the config window. The slider does not revert back to original value when opening config window the 2nd time. The model and view get out of sync.

**Comment by orozcoadrian** [comment]
yea i noticed the cancel case in the config window too. should fix that before merging this branch

**Comment by orozcoadrian** [comment]
you set me as an 'assignee'. should i be just a reviewer instead?

**Comment by codeTravels** [comment]
yea reviewer sorry

**Pull request merged**
